project:
  type: book

book:
  title: "Biología de las plantas: manual de laboratorio"
  output-file: "bdlp_manual"
  author: 
    - name: "Álex Espinosa-Correa"
      email: alex.espinosa@udea.edu.co
      orcid: 0000-0002-7353-1182
      affiliation:
      - id: udea
        name: |
          Grupo de Estudios Botánicos GEOBOTA, Instituto de Biología, 
          Facultad de Ciencias Exactas y Naturales, Universidad de Antioquia UdeA, 
          Calle 70 No. 52-21, Medellín, Colombia.
        url: https://geobota.github.io/
      url: https://geobota.github.io/people/alzate-guarin_fernando-alveiro/
    - name: "Felipe Alfonso Cardona-Naranjo"
      email: felipe.cardona@udea.edu.co
      orcid: 0009-0008-6232-7371
      affiliation:
        - ref: udea
      url: https://geobota.github.io/people/cardona-naranjo_felipe-alfonso/
    - name: "Fernando Alveiro Alzate-Guarín"
      email: alveiro.alzate@udea.edu.co
      orcid: 0000-0002-4916-8897
      affiliation:
        - ref: udea
      url: https://alexespinosaco.github.io/

  date: last-modified
  date-format: iso
  
  cover-image: images/cover.png
  page-navigation: true
  search: true
  reader-mode: true
  
  site-url: https://geobota.github.io/biologia-plantas-manual/
  repo-url: https://github.com/geobota/biologia-plantas-manual/
  downloads: [pdf]
  #sidebar: 
    #align: center
    #logo: images/cover.png

  google-analytics:
    tracking-id: "G-ZMDTRMYQMG"
    anonymize-ip: true
  
  twitter-card:
    card-style: summary_large_image

  open-graph: true

  chapters:
    - index.qmd
    - recorrido.qmd
    - microscopia.qmd
    - citologia.qmd
    - histologia-I.qmd
    - histologia-II.qmd
    - diversidad.qmd
    - raiz.qmd
    - tallo.qmd
    - hoja.qmd
    - flor.qmd
    - fruto.qmd
    - recursos.qmd
    - referencias.qmd

bibliography: references.bib
csl: apa.csl

comments: 
  hypothesis:
    theme: clean

lang: es

lightbox: true

crossref:
  fig-prefix: Fig.
  title-delim: "."

format:
  html:
    theme: 
      light: cosmo
      dark: solar
    # css: styles.scss
    # mainfont: "Atkinson Hyperlegible"
    link-external-icon: false
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt
    papersize: letter
    geometry:
      - hmargin=2.5cm
      - top=2.5cm
      - bottom=2.5cm
      - marginpar=2.5cm
    link-citations: true
    mainfont: "Atkinson Hyperlegible"
    fontsize: 12pt
    linkcolor: blue
    urlcolor: blue
    citecolor: blue
    filecolor: blue

nocite: |
  @bowes2013, @christenhusz2017, @dávilavillamizar2003, @dickison2000, @evert2006, 
  @evert2013, @fontquer2001, @graham2013, @jones2012, @mauseth2016, @nabors2006, 
  @paniagua2007, @pendarvis2018, @pérez-garcía2002, @schweingruber2006, 
  @schweingruber2011, @schweingruber2013, @simpson2019, @singh2019 
