# Histología II

## Introducción

![Corte transversal de *Cyperus papyrus* con Safranina y Azul Alcián. ae:
aerénquima, ch: clorénquima, ep: epidermis, es: esclerénquima, fl: floema, xi:
xilema.](images/tallo_cyperus_200x.png){#fig-tallo-cyperus
fig-align="center" width="6in"}

El **colénquima** y el **esclerénquima** son tejidos de soporte mecánico que
aportan flexibilidad y rigidez a la planta. El colénquima está constituido por
células vivas con engrosamientos de la pared primaria y la lámina intermedia.
Está presente en órganos jóvenes de las plantas en pecíolos y tallos. Se
originan a partir de los meristemos apicales e intercalares, también del
parénquima. Existen varios tipos de colénquima dependiendo de las
características y grado de engrosamiento, son cuatro tipos básicos: colénquima
**angular**, **anular**, **laminar** y **lagunar**.

El tejido esclerenquimático está constituido por células con engrosamiento de la
pared secundaria y con impregnación de lignina. Dependiendo del grado de
maduración, las células progresivamente pierden el citoplasma y mueren. Este
tejido es responsable de dar al cuerpo vegetal rigidez y resistencia. El
esclerénquima se origina a partir de los meristemos apicales, intercalares, del
parénquima y de la protodermis. Está constituido por dos tipos celulares: fibras
y esclereidas, las fibras son células alargadas que se pueden distribuir por
todo el cuerpo de la planta, formando paquetes o cordones. Se asocian por lo
general a la médula, corteza, xilema, floema y el cambium. Las esclereidas son
células cortas de forma variable, por lo cual se han clasificado en
braquiesclereidas, macroesclereidas, astroesclereidas, osteoesclereidas y
tricoesclereidas. Se pueden encontrar en cualquier parte del cuerpo vegetal,
aunque son más abundantes en hojas, tallos y frutos.

El **tejido vascular** en plantas está constituido por dos componentes
principales, el **xilema** y el **floema**, encargados del transporte de agua y
sales minerales disueltas y los fotosintatos respectivamente.

El xilema está formado por células muertas de dos tipos: las traqueidas y las
tráqueas. Las **traqueidas** son los elementos xilemáticos con mayor presencia
en plantas vasculares sin semilla (pteridofitos) y son los elementos únicos de
conducción en las gimnospermas. Las **tráqueas** también llamadas elementos de
los vasos se encuentran principalmente en angiospermas, aunque, también están
presentes en pteridófitos. Estos elementos vasculares se diferencian por su
anatomía y estructura; normalmente las traqueidas son más largas y presentan
forma de aguja y no tienen placas perforadas en los extremos terminales en el
contacto entre cada célula, por consiguiente, el transporte queda reducido a la
eficacia del paso del agua a través de las punteaduras. En contraste, las
tráqueas además de las punteaduras presentan una **placa perforada** en la parte
terminal de la célula. Tanto las traqueidas como las tráqueas presentan
engrosamientos del tipo anular, helicado, doblemente helicado, escaleriformes,
reticulado y punteado.

El tejido floemático está constituido por dos tipos celulares: las **células
floemáticas o tubos cribosos** y las **células anexas o acompañantes**. Ambas
son células vivas, pero el floema se ha diferenciado y ha perdido la mayor parte
de los organelos celulares y el núcleo. En la zona terminal de contacto entre
los tubos cribosos se desarrolla un **placa cribosa** que media el transporte
entre las células.

## Objetivo

-   Introducir al estudiante en los aspectos morfológicos, anatómicos y
    estructurales relacionados con los diferentes tipos de colénquimas, fibras
    esclerenquimáticas, esclereidas y los tejidos conductores en plantas.

-   Caracterizar la estructura típica del tejido colenquimático y
    esclerenquimático.

-   Caracterizar la estructura típica del tejido xilemático y floemático.

-   Reconocer la diversidad de formas y tamaños celulares encontrados en los
    tejidos objeto de estudio.

-   Reconocer los diferentes tipos de haces vasculares encontrados en
    traqueófitas.

## Materiales

### Reactivos y utensilios

-   Agujas de disección
-   Cubreobjetos y portaobjetos
-   Cuchillas
-   Lanilla o toalla
-   Microscopio
-   Pinceles de punta fina
-   Pinzas de punta fina
-   Solución de Azul Alcián
-   Solución de Azul de Toluidina
-   Solución de Glicerol al 30%
-   Solución de Safranina

### Material vegetal

-   Fruto de [*Pyrus communis*](https://tropicos.org/name/27800339) (Pera)
-   Hoja y pecíolo de [*Monstera deliciosa*](https://tropicos.org/name/2103116)
    (Balazo)
-   Hojas de [*Sansevieria trifasciata*](https://tropicos.org/name/18403542)
    (Lengua de Suegra)
-   Hojas y tallos de [*Apium graveolens*](https://tropicos.org/name/1700014)
    (Apio)
-   Hojas y tallos de [*Begonia spp.*](https://tropicos.org/name/40025930)
-   Hojas y tallos de [*Bidens pilosa*](https://tropicos.org/name/2700301)
    (Cadillo)
-   Hojas y tallos de [*Coriandrum sativum*](https://tropicos.org/name/1700064)
    (Cilantro)
-   Hojas y tallos de [*Cucurbita máxima*](https://tropicos.org/name/50172465)
    (Auyama o Zapallo)
-   Hojas y tallos de [*Cyperus papyrus*](https://tropicos.org/name/9902745)
    (Papiro)
-   Hojas y tallos de [*Lactuca sativa*](https://tropicos.org/name/2710604)
    (Lechuga)
-   Hojas y tallos de [*Mentha × piperita*](https://tropicos.org/name/17600157)
    (Menta) o [*Mentha spicata*](https://tropicos.org/name/17600159)
    (Hierbabuena)
-   Hojas y tallos de [*Pennisetum
    purpureum*](https://tropicos.org/name/25509854) (Pasto de Elefante) o
    cualquier otra [Poaceae](https://tropicos.org/name/42000357)
-   Hojas y tallos de [*Petroselinum
    crispum*](https://tropicos.org/name/50323572) (Perejil)
-   Hojas y tallos de [*Sambucus nigra*](https://tropicos.org/name/6000026)
    (Sauco)
-   Hojas y tallos de [*Taraxacum
    officinale*](https://tropicos.org/name/2726999) (Diente de León)
-   Ramas de [*Pinus spp.*](https://tropicos.org/name/40009142) (Pino)
-   Semillas frescas e hidratadas de [*Phaseolus
    vulgaris*](https://tropicos.org/name/13031753) (Frijol)
-   Tallos de [*Aristolochia ringens*](https://tropicos.org/name/2500164)

## Procedimiento

Se ha de realizar un registro detallado de todo lo observado, así como responder
las preguntas orientadoras. No olvide revisar la guía. El no conocer el material
vegetal, no es una excusa válida para no llevarlo al laboratorio. Revise en la
red, para observación de fotografías y nombres oficiales de las plantas en
páginas especializadas. Muchos ejemplares solicitados para el laboratorio se
encuentran en el campus universitario, en parques y jardines de la ciudad y/o en
herboristerías, supermercados y viveros.

### Observación del tejido colenquimático

-   Realice cortes transversales de peciolos o tallos de *Apium graveolens*,
    *Begonia spp.*, *Bidens pilosa*, *Coriandrum sativum*, *Cucurbita máxima*,
    *Lactuca sativa*, *Mentha × piperita*, *Petroselinum crispum*, *Sambucus
    nigra* y *Taraxacum officinale*. Tiña con Safranina y Azul Alcián, observe
    la presencia de los diferentes tipos de colénquima asociados a estos órganos
    vegetativos. ¿Las células del colénquima presentan citoplasma funcional?
    ¿Todos los órganos vegetales observados tienen los mismos tipos de
    colénquimas y ocupando la misma topografía? ¿Qué características de tinción
    presenta este tejido que lo diferencia de los demás tejidos, al utilizar
    Safranina y Azul Alcián?

![Corte transversal de tallos de *Apium graveolens* con Safranina y Azul Alcián.
co: colénquima, es: esclérenquima, fl: floema, pa: parénquima, xi:
xilema.](images/tallo_apium_200x.png){#fig-tallo-apium
fig-align="center" width="6in"}

![Corte transversal de tallos de *Cucurbita máxima* con Safranina y Azul Alcián.
co: colénquima, es: esclérenquima, pa: parénquima, xi:
xilema.](images/tallo_cucurbita_200x.png){#fig-tallo-cucurbita
fig-align="center" width="6in"}

### Observación del tejido esclerenquimático

-   Realice cortes transversales de tallos maduros de *Aristolochia ringens*,
    tiña con Safranina y Azul Alcián. Observe la presencia de **fibras
    esclerenquimáticas** formando paquetes o cordones en la corteza entre el
    parénquima. Repita el mismo procedimiento pero con tallos de *Bidens pilosa*
    y *Cyperus papyrus* y hojas de *Sansevieria trifasciata* y *Pennisetum
    purpureum*. Aprecie la presencia de los mismos paquetes de fibras
    esclerenquimáticas y la formación de vainas alrededor de los haces
    vasculares. ¿Qué tipos de fibras esclerenquimáticas se pueden encontrar en
    el cuerpo vegetal?

-   Realice cortes transversales del fruto de *Pyrus communis*, tiña con
    Safranina y Azul Alcián. Se observa la presencia de **braquiesclereidas**,
    inmersas dentro del parénquima de reserva formando paquetes. Estas células
    son cortas, de paredes muy engrosadas, con abundante lignina y varias
    punteaduras en la pared celular. ¿Cuál es la función de las esclereidas?
    ¿Qué son las células pétreas? ¿Qué son las punteaduras? ¿Qué es un
    plasmodesmo?

-   Realice cortes transversales de la testa de *Phaseolus vulgaris*, tiña con
    Safranina y Azul Alcián. Observe e identifique los diferentes tipos de
    **esclereidas** que forman parte de las cubiertas seminales.

-   Realice cortes transversales de las hojas de *Monstera deliciosa*, tiña con
    Safranina y Azul Alcián. ¿Qué tipo de esclereidas se pueden detectar en
    estos preparados? ¿Estas células se encuentran inmersas en qué tipo de
    tejido?

![Corte transversal de *Aristolochia ringens* con Safranina y Azul Alcián. ep:
epidermis, es: esclrénquima, pa:
parénquima.](images/tallo_aristolochia_200x.png){#fig-tallo-aristolochia
fig-align="center" width="6in"}

### Observación de xilema y floema

![Haz vascular de *Aristolochia ringens* con Safranina y Azul Alcián. ca:
cámbium, es: esclérenquima, fl: floema, pa: parénquima, xi:
xilema.](images/vascular_aristolochia_200x.png){#fig-vascular-aristolochia
fig-align="center" width="6in"}

-   Realice cortes transversales y longitudinales finos del tallo en diferentes
    etapas de maduración de *Aristolochia ringens* y *Cucurbita máxima*, tiña
    con Safranina y Azul Alcián (montando en glicerol, también puede utilizar
    Azul de Toluidina). En ambos casos identifique el **metaxilema** y
    **protoxilema**, diferenciándolos estructuralmente de los demás tejidos
    presentes en el cuerpo de la planta. Así mismo, en corte longitudinal,
    identifique los diferentes tipos de **engrosamientos** presentes en las
    paredes laterales del protoxilema (anular, ánulo-helicada, doblemente
    helicado, helicado,) y metaxilema (escaleriforme, punteado, reticulado).
    Este tipo de engrosamientos se pueden encontrar tanto en tráqueas como
    traqueidas, excepto el reticulado, exclusivo de las tráqueas.

-   Realice cortes transversales y longitudinales de los tallos de *Pinus ssp*.
    Tiña con Safranina y Azul Alcián y observe la presencia de traqueidas, como
    elementos xilemáticos exclusivos de las gimnospermas. Las traqueidas por lo
    general presentan engrosamientos tipo punteadura que puede ser simple o
    areolada, es decir, formando una aréola alrededor de la perforación y esta
    puede tener **toro**.\
    ¿Qué diferencias ontogenéticas en los tejidos vasculares se pueden apreciar
    entre los tallos maduros e inmaduros de una misma planta? ¿Cuál es la
    función de los engrosamientos presentes en el xilema? ¿Cuáles son las
    diferencias anatómicas, estructurales y fisiológicas entre tráqueas y
    traqueidas? ¿Qué es el toro, presente en las punteaduras areoladas de
    gimnospermas? ¿Qué diferencias existen entre engrosamientos presentes en el
    xilema y los campos de punteaduras primarias y secundarias?

-   En cortes transversales como longitudinales *Aristolochia ringens* fije su
    atención en las en el tejido floemático e identifique los **tubos cribosos**
    o **células cribosas** y las **áreas cribosas** o **placas cribosas**
    presentes en la región terminal de cada tubo criboso. También detecte la
    presencia de las células anexas o acompañantes del tubo criboso. En corte
    transversales de estas mismas plantas, observe la presencia del **cambium
    vascular** entre el xilema y floema, este tejido es fácil de diferenciar por
    el arreglo regular y la forma cuadrangular/rectangular que tienen las
    células. Observe entre los haces vasculares la presencia del **cambium
    interfascicular**.\
    ¿Qué diferencias fisiológicas, anatómicas y estructurales se presentan entre
    floema y xilema? ¿En las monocotiledóneas que tejidos generan xilema y
    floema cuando el procambium se ha diferenciado? ¿Qué es el procambium y cuál
    es el origen de este tejido?

![Haz vascular de *Cyperus papyrus* con Safranina y Azul Alcián. es:
esclérenquima, fl: floema, pa: parénquima, xi:
xilema.](images/vascular_cyperus_400x.png){#fig-vascular-cyperu
fig-align="center" width="6in"}
