# Hoja

## Introducción

La hoja es un órgano vegetativo que se desarrolla de un **primordio foliar**, el cuál es un crecimiento lateral de las **yemas**. La mayoría de las hojas son de aspecto laminar, pero las hay también acumulares y escamosas entre otras. Existe gran variedad de hojas en cuanto a la forma, número de limbos, venación, filotaxia, borde, base y ápice.

## Objetivo

-   Identificar los tejidos presentes en la hoja y su variación en los diferentes grupos de plantas. 

-   Identificar la estructura externas de las hojas.

-   Reconocer la gran diversidad morfológica de las hojas.

## Materiales

### Reactivos y utensilios

-   Agujas de disección
-   Cajas de Petri
-   Cubreobjetos y portaobjetos
-   Cuchillas
-   Estereomicroscopio
-   Lanilla o toalla
-   Microscopio
-   Pinceles de punta fina
-   Pinzas de punta fina
-   Solución de Azul Alcián
-   Solución de Glicerol al 30%
-   Solución de Safranina

### Material vegetal

-   Hojas y ramas de diferentes grupos de Angiospermas y Gimnospermas
-   Placas permanentes con cortes de hojas

## Procedimiento

Se ha de realizar un registro detallado de todo lo observado, así como responder las preguntas orientadoras. No olvide revisar la guía. El no conocer el material vegetal, no es una excusa válida para no llevarlo al laboratorio. Revise en la red, para observación de fotografías y nombres oficiales de las plantas en páginas especializadas. Muchos ejemplares solicitados para el laboratorio se encuentran en el campus universitario, en parques y jardines de la ciudad y/o en herboristerías, supermercados y viveros.

### Morfología externa de una hoja

-   En la rama de una planta cualquiera, observe bien una hoja e identifique lo siguiente: ápice, base, cara adaxial, cara abaxial, estípula, -   lámina, margen, pecíolo, venación, yema axilar.

### Morfología Externa de una Hoja de Monocotiledónea

-   Observe hojas de diferentes Monocotiledóneas e identifique similitudes y diferencias entre las especies. Estas variaciones pueden corresponder a venación, forma, forma de unión al tallo, presencia de peciolo, entre otras.

### Estructura Interna de la Hoja

-   Realice cortes transversales en diferentes hojas de Eudicotiledóneas, Gimnospermas y Monocotiledóneas. Tiña con Safranina y Azul Alcián. Observe e identifique diferencia y similitudes, además de las siguientes estructuras: cutícula, epidermis, parénquima en empalizada, parénquima esponjoso y tejidos vasculares (nervaduras).

### Diversidad en las Hojas

-   Observe la mayor cantidad posible de hojas de diferentes especies de Gimnospermas. Haga observaciones comparativas entre los diferentes tipos (tenga en cuenta venación, peciolo, forma y disposición).

-   Observe la mayor cantidad posible de hojas de diferentes especies de Angiospermas, realice observaciones comparativas teniendo en cuenta:
    -   Ápice: agudo, acuminado, obtuso, etc.
    -   Base: aguda, cordada, obtusa, etc.
    -   Estípulas: presencia o ausencia.
    -   Filotaxia: alterna, opuesta, verticilada, etc.
    -   Forma: elíptica, lanceolada, linear, etc.
    -   Margen: dentado, entero, serrado, etc.
    -   Pecíolo: peciolada, sesil, subpeciolada, etc.
    -   Tipo de hoja: simple o compuesta, si es compuesta indique el tipo exacto.
    -   Venación: actinodromo, braquidodromo, craspedodromo, etc.
