# Diversidad II
<!--# el procedimiento de esta práctica podría ser diferente, preguntar a los otros -->
## Introducción

El grupo de plantas **Spermatophyta** está conformado por las **Gymnospermae** y **Angiospermae** y es el más reciente evolutivamente. Estas plantas poseen algunas sinapomorfías que las definen, pero su principal carácter evolutivo es el desarrollo de la semilla, para lo cual primero debieron realizar algunas novedades evolutivas como son: **evolución del tegumento**, **endosporia**, **heterosporia**, **reducción de la megaspora a una**, **retención de la megaspora**. Las Spermatophyta cuentan con cerca de 300000 especies distribuidas por todo el mundo y agrupadas en un amplio número de linajes.

### Gymnospermae

Las Gymnospermae son un grupo de plantas leñosas, en su mayoría arbóreas y aromáticas, las cuales desarrollan semillas. A nivel del xilema solo desarrollan traqueidas, sin producción de flores ni frutos. Estas plantas son en mayor proporción anemófilas en cuanto a su polinización y dispersión. Tres divisiones se reconocen actualmente dentro de Gymnospermae que son: **Cycadophyta**, **Ginkgophyta** y **Coniferophyta**. En conjunto las Gimnospermas tienen aproximadamente 820 especies, con su mayor diversidad en zonas templadas de la zona holártica.

Las Angiospermae son el grupo más reciente y el más diverso (ca. 280000 especies) de las plantas. La principal innovación evolutiva de las Angiospermas es el desarrollo de la flor, mediante la cual se han permitido muchas relaciones con la fauna y ello ha favorecido la especialización en la polinización y dispersión y por ende en la especiación. Otros caracteres desarrollados por las Angiospermas son las **tráqueas** o **vasos del xilema** y las **células acompañantes del tubo criboso**. La doble fecundación es compartida por las Angiospermas conjuntamente con un pequeño grupo de Gimnospermas.

Las Angiospermas fueron inicialmente divididas en dos grandes grupos: **Monocotiledónea** y **Dicotiledónea**, de acuerdo al número de cotiledones presentes en la semilla. Sin embargo el agrupamiento de las dicotiledóneas no se soporta, ya que constituyen un grupo parafilético, además en este grupo de plantas se desarrollan también más de dos cotiledones. Las más recientes propuestas clasificatorias para las Angiospermas, planteadas por APG IV [-@theangiospermphylogenygroup2016], incluyen los siguientes principales grupos naturales:

-   Magnoliids
-   Monocots
    -   Commelinids
-   Eudicots
    -   Superrosids
        -   Rosids
            -   Fabids
            -   Malvids
    -   Superasterids
        -   Asterids
            -   Campanulids
            -   Lamiids

Falta aún clarificar las relaciones existentes para varios grupos dentro de las plantas con flor, pero un esquema amplio ya ha sido adecuadamente sustentado por diferentes análisis filogenéticos.

## Objetivo

-   Reconocer y caracterizar morfológica y anatómicamente los diferentes linajes de plantas Embriophyta, discriminando las variables en cuanto a alternancia de generaciones y reproducción.

## Materiales

### Reactivos y utensilios

-   Agujas de disección
-   Cajas de Petri
-   Cubreobjetos y portaobjetos
-   Cuchillas
-   Estereomicroscopio
-   Lanilla o toalla
-   Microscopio
-   Pinceles de punta fina
-   Pinzas de punta fina
-   Solución de Azul Alcián
-   Solución de Glicerol al 30%
-   Solución de Safranina

### Material vegetal

-   Especímenes de Coniferophyta
-   Especímenes de Cycadophyta
-   Especímenes de Eudicots
-   Especímenes de Magnoliids
-   Especímenes de Monocots

## Procedimiento

### Gymnospermae

-   Tome ejemplares pertenecientes a los dos grandes grupos de Gimnospermas presentes en Colombia (Cycadophyta y Coniferophyta) y describa los siguientes caracteres morfológicos para cada una de las divisiones:
    -   Hábito
    -   Complejidad foliar
    -   Filotaxia
    -   Peciolo
    -   Polen
-   Realice conclusiones en cuanto a los caracteres que permiten reconocer las divisiones mencionadas.

### Angiospermae

-   Examine ejemplares pertenecientes a los siguientes grupos de Angiospermas:
    -   **Magnolidos** (Piperaceae, Anonnaceae, Magnoliaceae)
    -   **Monocotiledónea** (Petaloideas, Apetalas y Zingiberoides)
    -   **Rosidae** (Leguminosas, Rosaceae)
    -   **Asteridae** (Bignoniaceae, Asteraceae)
-   Describa los siguientes caracteres morfológicos para cada uno de los grupos planteados:
    -   Hábito
    -   Complejidad foliar
    -   Filotaxia
    -   Componentes florales:
        -   Número de verticilos
        -   Número de componentes de cada verticilo
        -   Fusión de componentes del perianto
        -   Simetría floral
    -   Polen:
        -   Aberturas
        -   Forma
        -   Ornamentación
-   Realice conclusiones en cuanto a los caracteres que permiten reconocer los grupos propuestos.
