# Flor

## Introducción 

La flor contiene las estructuras encargadas de la reproducción sexual en las Angiospermas. Basados en lo anterior podemos definir la flor como una rama con eje corto que posee hojas modificadas distribuidas en verticilos encargados en su conjunto de la reproducción sexual.

## Objetivo

-   Identificar cada una de las estructuras de una flor y explicar sus adaptaciones e importancia para la reproducción.

-   Comprobar la diversidad en la Estructura y distribución de las flores y relacionarlas con su función.

## Materiales

### Reactivos y utensilios

-   Agujas de disección
-   Cajas de Petri
-   Cubreobjetos y portaobjetos
-   Cuchillas
-   Estereomicroscopio
-   Lanilla o toalla
-   Microscopio
-   Pinceles de punta fina
-   Pinzas de punta fina
-   Solución de Azul Alcián
-   Solución de Fuscina básica
-   Solución de Glicerol al 30%
-   Solución de Sacarosa al 10%
-   Solución de Safranina

### Material vegetal

-   Ramas con flores de [*Calliandra spp.*](https://tropicos.org/name/13004713) (Carbonero)
-   Ramas con flores de [*Crotalaria spp.*](https://tropicos.org/name/40016956) (Cascabelito)
-   Ramas con flores de [*Eucalyptus spp.*](https://tropicos.org/name/40006486) (Eucalipto)
-   Ramas con flores de [*Handroanthus spp.*](https://tropicos.org/name/40020733) o [*Tabebuia sp.*](https://tropicos.org/name/40009350) (Guayacán)
-   Ramas con flores de [*Helianthus annuus*](https://tropicos.org/name/2700851) (Girasol)
-   Ramas con flores de [*Hemerocallis spp.*](https://tropicos.org/name/40023307) (Lirio)
-   Ramas con flores de [*Hibiscus rosa-sinensis*](https://tropicos.org/name/19600046) (San Joaquín)
-   Ramas con flores de [*Impatiens balsamina*](https://tropicos.org/name/3100102) (Besito)
-   Ramas con flores de [*Mangifera indica*](https://tropicos.org/name/1300071) (Mango)
-   Ramas con flores de [*Nerium oleander*](https://tropicos.org/name/1800765) (Adelfa, Azucena de La Habana)
-   Ramas con flores de [*Salix humboldtiana*](https://tropicos.org/name/28300168) (Sauce)
-   Ramas con flores de [*Tradescantia pallida*](https://tropicos.org/name/8300409) (Guardaparque)
-   Ramas con flores de [*Zea mays*](https://tropicos.org/name/25510055) (Maíz)

## Procedimiento

### Morfología comparativa de flores de Eudicotiledóneas y Monocotiledónea

-   Seleccione una flor de Eudicotiledóneas y Monocotiledóneas, en cada una observe e identifique el pedúnculo y el receptáculo, igualmente identifique cada uno de los verticilos y sus componentes: cáliz (sépalos), corola (pétalos), androceo (estambres), gineceo (carpelos). Con ello, responda las preguntas. ¿Cuántos componentes tiene cada uno de los verticilos? ¿Cuántos carpelos posee el ovario? ¿El ovario es simple o compuesto? ¿La flor unisexual o bisexual? ¿La flor es completa o incompleta? ¿La flor es perfecta o imperfecta? ¿Esta flor pertenece a una especie dioica o monoica? ¿Qué nombre recibe el conjunto de sépalos y pétalos? ¿Qué diferencias y similitudes morfológicas observa entre ambas flores?

### Diversidad en la flor

-   Observe la mayor cantidad de flores de varias plantas de diferente especie y realice observaciones comparativas teniendo en cuenta:
    -   Nombre científico
    -   Nombre vulgar
    -   Verticilos presentes: perianto (cáliz, corola), perigonio, androceo, gineceo.
    -   Número de componentes de cada verticilo: sépalos, pétalos, tépalos, estambres, carpelos.
    -   Flor completa o incompleta
    -   Flor perfecta o imperfecta
    -   Simetría: actinomorfa, irregular, zigomorfa.
    -   Número de carpelos
    -   Posición del ovario: ínfero, semi-ínfero, súpero,
    -   Sexo de la flor: unisexual, bisexual.
    -   Sexo en la especie: dioica, monoica.
    -   Flores solitarias o en inflorescencia
    -   Tipo de inflorescencia: espiga, capítulo, umbela, etc.

### El polen

-   Seleccione la antera de una flor de Eudicotiledóneas y Monocotiledónea, separadamente realice un montaje húmedo. Observe en 10x y 40x, posteriormente tiña con Fucsina básica e identifique la unidad polínica, aberturas, estructura, polaridad, simetría, forma y tamaño. ¿Qué diferencias observa en los montaje antes y después de colorear? ¿Qué diferencia hay entre el polen de Eudicotiledóneas y Monocotiledónea?

-   Prepare un montaje húmedo de polen de *Impatiens balsamina* o *Tradescantia pallida* en una gota de solución de sacarosa al 10%. Observe en 10X y 40X. Apague la lámpara y observe nuevamente cada cinco minutos. ¿Cuál es la explicación fisiológica de la formación del tubo polínico? ¿Qué parte del polen forma el tubo polínico? ¿Cuál es la función del tubo polínico?

<!-- 
Hay una parte que no inclí, quizá se pueda mejorar.

Estructura del Ovulo y Desarrollo del Saco Embrionario 
Observe la figura y consulte por su cuenta el proceso de polinización, fecundación y desarrollo del saco embrionario.
-->