# Tallo
<!--# el procedimiento de esta práctica podría ser diferente, preguntar a los otros -->
## Introducción

El crecimiento secundario del tallo determina un aumento de su diámetro y soporte en las plantas que lo presentan, permitiendo que vivan por muchos años. Se inicia con la formación de cambium vascular y cambium del corcho (felógeno). Ocurre en Gimnospermas, Eudicotiledóneas leñosas, algunas Eudicotiledóneas herbáceas (ej. girasol) y en pocas Monocotiledóneas (ej. palmas), aunque en estas últimas el cuerpo secundario tiene un origen diferente a las otras plantas leñosas.

Para el estudio de los tejidos de tallos se utilizan dos tipos de cortes o secciones: **sección transversal**, aquella que corta en ángulo recto al eje del tallo y **sección longitudinal**, que a su vez puede ser **radial** cuando pasa a lo largo del radio y **tangencial** cuando corta paralelamente al eje del tallo sin pasar por el centro.

En una sección radial los **anillos de crecimiento** aparecen como líneas más o menos paralelas y los radios como líneas que corren a través de ellos. En la sección tangencial los radios aparecen agrupados en forma de lentes y en la sección transversal los elementos de xilema y del floema se cortan transversalmente y se observan como poros de diferentes diámetros según el elemento a que corresponden.


## Objetivo

-   Explicar el desarrollo ontogenético del cuerpo secundario del tallo.

-   Diferenciar el cuerpo primario del cuerpo secundario de las plantas leñosas.

-   Interpretar las adaptaciones del tallo leñoso para la vida terrestre de la planta.

-   Diferenciar e interpretar las adaptaciones de un crecimiento secundario del tallo diferente al patrón general (tallos anómalos).


## Materiales

### Reactivos y utensilios

-   Agujas de disección
-   Cajas de Petri
-   Cubreobjetos y portaobjetos
-   Cuchillas
-   Estereomicroscopio
-   Lanilla o toalla
-   Microscopio
-   Pinceles de punta fina
-   Pinzas de punta fina
-   Solución de Azul Alcián
-   Solución de Glicerol al 30%
-   Solución de Safranina

### Material vegetal

-   Bloques de madera de Angiospermas y Gimnospermas
-   Placas permanentes con cortes del tallo
-   Placas permanentes con macerados de xilema
-   Tallos de [*Aristolochia ringens*](https://tropicos.org/name/2500164)
-   Tallos de [*Cupressus spp.*](https://tropicos.org/name/40018366) (Ciprés)
-   Tallos de de [*Salix humboldtiana*](https://tropicos.org/name/28300168) (Sauce)
-   Tallos de diferentes plantas
-   Tallos de [*Pinus spp.*](https://tropicos.org/name/40009142) (Pino)

## Procedimiento

### Estructura interna del cuerpo secundario de plantas leñosas

-   Realice un corte transversal del tallo de *Salix humboldtiana*. Tiña con Safranina y Azul Alcián. Observe e identifique los siguientes tejidos: súber, felógeno, felodermo, parénquima, floema secundario, cambium vascular y xilema secundario. ¿Qué ocurre con la epidermis durante el desarrollo del corcho? ¿De dónde se origina y cuál es la función del felógeno? ¿De cuáles células del cambium vascular se originan xilema y floema secundario? Explique el porqué de la naturaleza impermeabilizante del corcho.

### Estudio macroscópico del tallo con crecimiento secundario

-   Con la ayuda de un estereomicroscopio estudie los bloques, que le sean suministrados, de madera de tallos de angiospermas y de gimnospermas. Observe las diferencias entre los cortes transversal, radial y tangencial, distinga los anillos anuales, rayos del xilema, córtex, floema secundario, chorcho, cambium del corcho, región del cambium vascular, xilema secundario, madero de estación lluviosa, madera de estación seca, médula, variación en tamaños celulares y ductos de resina y mucílagos.

### Estructura interna del xilema secundario del tallo

-   Haga cortes transversales, radiales y tangenciales en tallos de *Cupressus spp.*, *Pinus spp.*, *Salix humboldtiana* y cualquier otra planta que presente crecimiento secundario. Tiña con Safranina y Azul Alcián. Observe y diferencie las características típicas de cada sección. Distinga los elementos de xilema, rayos del xilema, médula, madera de estación seca, madera de estación lluviosa y ductos de resina. Complemente sus observaciones con las placas permanentes con secciones y macerados de madera de Angiospermas y Gimnospermas ¿Qué diferencias y similitudes existen entre los cortes de tallos de Angiospermas y Gimnospermas? ¿Cuáles células forman el xilema en Angiospermas y Gimnospermas?

### Tallos anómalos

-   Haga cortes transversales de tallos de *Aristolochia ringens* y otras plantas trepadoras o bejucos, tiña con Safranina y Azul Alcián. Observe e identifique las diferencias que presentan con relación al patrón común de los otros tallos estudiados y determine las diferentes localizaciones de floema secundario, xilema secundario y médula. ¿A qué se debe el crecimiento anómalo de estos tallos? ¿Qué adaptaciones podrían ser interpretadas para este tipo de crecimiento? Describa la forma adoptada por el xilema secundario en cada tipo de corte suministrado.
