# Citología

## Introducción

Desde la visualización por primera vez de la célula vegetal por Robert Hooke en el siglo XVII, quien precisamente acuñó el término célula, hasta nuestros días el estudio citológico tanto en animales como en vegetales ha dado grandes pasos que están relacionados directamente con el avance en instrumentos y técnicas que han aportado las herramientas necesarias para esclarecer toda la conformación estructural, ultraestructural, bioquímica y molecular de las células. La célula vegetal está constituida de cuatro elementos básicos: La **pared celular**, formada por dos capas en células de crecimiento primario (Lámina primaria e intermedia) y por tres en células de crecimiento secundario (Lámina primaria, intermedia y secundaria), cada una de ellas con una constitución química y estructural definida. Como todas las células vivas, encontramos la **membrana celular** inmediatamente yuxtapuesta a la pared celular. El **citoplasma** dentro del cual se encuentran inmersos los organelos celulares comunes tanto a vegetales como animales (mitocondrias, peroxisomas, ribosomas) y constituyentes característicos pero no exclusivos de las células vegetales como plastidios que pueden ser fotosintéticos o de almacenamiento de alguna sustancia producto del metabolismo (aceites, almidón, látex, cristales). Finalmente encontramos el **núcleo celular** que contiene principalmente el ADN, algunas formas de ARN y nucleoproteínas.

Es importante aclarar que las diferencias entre las células en cuanto a estructura, función y diversidad que conforman el cuerpo vegetal, está regido por dos por la interacción genotipo/ medio ambiente, lo que conlleva a la expresión genética diferencial.

## Objetivo

-   Introducir al estudiante en los aspectos morfológicos, anatómicos y estructurales relacionados con la célula vegetal.

-   Caracterizar la estructura típica de las células vegetales.

-   Reconocer la diversidad de formas y tamaños celulares encontrados en el cuerpo de las plantas.

-   Identificar cualitativamente algunos compuestos orgánicos presentes en las células vegetales.

## Materiales

### Reactivos y utensilios

-   Agujas de disección
-   Cubreobjetos y portaobjetos
-   Cuchillas
-   Lanilla o toalla
-   Mecheros de alcohol
-   Pinceles de punta fina
-   Pinzas de punta fina
-   Solución de Azul Alcián
-   Solución de Glicerol al 30%
-   Solución de Lugol
-   Solución de Safranina
-   Solución de Sudan III o Sudan negro

### Material vegetal

-   Bulbo de [*Allium cepa*](https://tropicos.org/name/18401646) (Cebolla de huevo)
-   Fruto de [*Capsicum annuum*](https://tropicos.org/name/29600002) (Pimentón rojo)
-   Fruto de [*Solanum lycopersicum*](https://tropicos.org/name/29605838) (Tomate)
-   Hojas de [*Ficus elastica*](https://tropicos.org/name/21302161) (Caucho)
-   Hojas y tallos de [*Tradescantia pallida*](https://tropicos.org/name/8300409) (Guardaparque)
-   Pecíolos y hojas de [*Begonia spp.*](https://tropicos.org/name/40025930)
-   Pétalos de diferentes colores
-   Ramas de [*Egeria densa*](https://tropicos.org/name/16100033) (Elodea)
-   Ramas de [*Impatiens balsamina*](https://tropicos.org/name/3100102)
-   Ramas de [*Pinus spp.*](https://tropicos.org/name/40009142)
-   Semillas frescas de [*Phaseolus vulgaris*](https://tropicos.org/name/13031753) (Frijol)
-   Semillas frescas de [*Zea mays*](https://tropicos.org/name/25510055) (Maíz)
-   Semillas hidratadas de [*Triticum aestivum*](https://tropicos.org/name/25510034) (Trigo)
-   Tallos de [*Daucus carota*](https://tropicos.org/name/1701516) (Zanahoria)
-   Tallos de [*Aristolochia ringens*](https://tropicos.org/name/2500164)
-   Tubérculo de [*Manihot esculenta*](https://tropicos.org/name/12800237) (Yuca)
-   Tubérculo de [*Solanum tuberosum*](https://tropicos.org/name/29600334) (Papa)

## Procedimiento

Se ha de realizar un registro detallado de todo lo observado, así como responder las preguntas orientadoras. No olvide revisar la guía. El no conocer el material vegetal, no es una excusa válida para no llevarlo al laboratorio. Revise en la red, para observación de fotografías y nombres oficiales de las plantas en páginas especializadas. Muchos ejemplares solicitados para el laboratorio se encuentran en el campus universitario, en parques y jardines de la ciudad y/o en herboristerías, supermercados y viveros.

### Identificación de Lignina

-   Realice cortes transversales finos del tallo de *Aristolochia ringens*, agregue una gota de Safranina, tiña por 1 minuto retire el exceso de colorante y lave con agua destilada, retire el agua y agregue una gota de Azul Alcián, lave nuevamente con agua destilada y monte en una gota de Glicerol. Estos dos reactivos pueden venir en uno solo ya preparado. Observe al microscopio en 10x, 40x y si es necesario en 100x. Se nota la aparición de una coloración roja o púrpura, esto demuestra la presencia de lignina. ¿Qué tejidos presentan reacción positiva?

### Reconocimiento de sustancias lipídicas

-   Realice cortes transversales finos del tallo de *Pinus spp.* agregue una gota de Sudan III o Sudan negro y caliente la lámina suavemente acercándola al mechero. Observe al microscopio en 10x, 40x y si es necesario en 100x. Se nota la aparición de un color rojo/naranja por la presencia de lípidos.

-   Realice cortes transversales finos de las hojas de *Ficus elástica* y proceda como lo anterior. Debe observa la presencia de una capa acelular de color rojizo o naranja que corresponde a la cutícula constituida principalmente de cutina.

¿Cuál es la función de las sustancias y estructuras identificadas en esta sección del Laboratorio?

### Estructura, Formas, diversidad e inclusiones citoplasmáticas

-   Tome un estambre de la flor de *Tradescantia pallida* y descarte la antera. Coloque el filamento en un portaobjetos con una gota de agua y cubra con un cubreobjetos (montaje húmedo). Enfoque el objetivo de 10x y concentre su observación en las prolongaciones laterales que se disponen a manera de cadena. Estas estructuras se denominan tricomas. Observe con objetivo 40X e identifique las siguientes estructuras: pared celular, vacuola, núcleo y citoplasma.

-   Prepare un montaje húmedo de una hoja de *Egeria densa* con agua de su medio natural. Observe con 10x y 40x y localice las siguientes estructuras: Pared celular, citoplasma y cloroplastos. Observe la unión de dos células contiguas e identifique la laminilla media.

¿Cuál es la composición química de la laminilla media? ¿Cuál es la composición Química de la pared? ¿Qué tipos de pared puede tener una célula? Observe los cloroplastos. ¿En cuál parte de la célula se localizan éstos? ¿Qué función desempeñan en la planta?

-   Elabore varios cortes finos de la superficie inferior de un pétalo de una flor amarilla, roja o de otro color agregue una gota de agua y observe en los aumento que sea necesario. ¿Es posible identificar cromoplastos?

Repita el procedimiento anterior, pero utilizando los tallos de *Daucus carota*, epidermis del fruto de *Capsicum annuum* y epidermis o mesocarpo de *Solanum lycopersicum*. ¿Qué tipos de plastidios se observa?, ¿cuáles son sus funciones?

-   Realice cortes finos de los cotiledones de *Phaseolus vulgaris* agregue una gota de agua y otra de Lugol observe al microscopio en los aumentos que sea necesario, la aparición de una coloración violácea o negra determina la presencia de almidón dentro de los amiloplastos. Para observar la presencia del hilo y las laminillas concéntricas en los amiloplastos es mejor hacer un montaje sin teñir sólo agregando agua.

Repita el procedimiento anterior, pero utilizando las semillas de *Triticum aestivum*, *Zea mays*, el tubérculo de *Solanum tuberosum* y la raíz de *Manihot esculenta*.

Establezca comparaciones entre los diferentes amiloplastos y determine si existen diferencias.

-   Realice cortes transversales finos del peciolo de *Begonia spp.* agregando solo una gota de agua. Observe a diferentes aumentos. Se aprecia la presencia de cristales tipo drusas de oxalato de calcio en las células. También es posible ver la presencia de cristales en forma de aguja que corresponde a estiloides, paquetes de estiloides llamados rafidios y cristales romboédricos.

Repita el procedimiento anterior cortando los peciolos de *Impatiens balsamina*, en la epidermis de *Allium cepa* ¿Cuál es la función de estos cristales?

-   Realice cortes transversales finos de hojas maduras de *Ficus elástica*, agregue una gota de Safranina, tiña por 1 minuto retire el exceso de colorante y lave con agua destilada, retire el agua y agregue una gota de Azul Alcián, lave nuevamente con agua destilada y monte en una gota de Glicerol. Debe apreciar en la epidermis superior, pluriestratificada, la presencia de células especializadas en almacenar cistolitos que son agregados de carbonato de calcio. ¿Qué nombre recibe esta célula especializada que almacena los cistolitos?
